//! # DBus interface proxy for: `org.zbus.MyGreeter1`
//!
//! This code was generated by `zbus-xmlgen` `3.1.0` from DBus introspection data.
//! Source: `Interface '/org/zbus/MyGreeter' from service 'org.zbus.MyGreeter' on session bus`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This DBus object implements
//! [standard DBus interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//! * [`zbus::fdo::PeerProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use zbus::dbus_proxy;

#[dbus_proxy(
    interface = "org.zbus.MyGreeter1",
    default_service = "org.zbus.MyGreeter",
    default_path = "/org/zbus/MyGreeter"
)]
trait MyGreeter1 {
    /// GoAway method
    fn go_away(&self) -> zbus::Result<()>;

    /// SayHello method
    fn say_hello(&self, name: &str) -> zbus::Result<String>;

    /// GreetedEveryone signal
    #[dbus_proxy(signal)]
    fn greeted_everyone(&self) -> zbus::Result<()>;

    /// FailingProperty property
    #[dbus_proxy(property)]
    fn failing_property(&self) -> zbus::Result<String>;

    /// CouldFail property
    #[dbus_proxy(property)]
    fn could_fail(&self) -> zbus::Result<String>;

    /// GreeterName property
    #[dbus_proxy(property)]
    fn greeter_name(&self) -> zbus::Result<String>;
    fn set_greeter_name(&self, value: &str) -> zbus::Result<()>;
}
